### PR TITLE
Add and tune normalize json

### PR DESCRIPTION
**Pull request by Poeschl**
After updating my normalize rules on some projects I wanted to share the changes with you.
All new matchers come from the [test project](https://github.com/Poeschl/Licence-Rule) which includes over 400 dependencies.

### CODE REVIEW

**Comment by guenhter** [comment]
Didn't you like your changes?

**Comment by Poeschl** [comment]
Will add some more stuff and reopen it after adding. 😉

**Comment by Poeschl** [comment]
Or I might create a new PR then 😅
To early for my brain today....

**Comment by jk1** [comment]
Thank you for the contribution.
To reduce the number of duplicates in `default-license-normalizer-bundle.json` I've changed the matcher to be case insensitive.

**Pull request merged**
