### PR TITLE
Bundle additions

### PR DESCRIPTION
**Pull request by Poeschl**
I added some groups and matchers for the bundle feature.
They might be also helpful to others.

### CODE REVIEW

**Comment by guenhter** [comment]
@Poeschl  If you think that your changes didn't make the changes fail, I'll have a look at them.

**Comment by Poeschl** [comment]
It might be my fault, will look into it ;) 
Just to be sure the matchers are pure regex matcher strings?

**Comment by guenhter** [comment]
It is done with 

`.findAll { it.licenseNamePattern && (name == it.licenseNamePattern || name ==~ it.licenseNamePattern) }`

https://github.com/jk1/Gradle-License-Report/blob/4fadcb484ad37e13f4a7811ad90b28adeec773a1/src/main/groovy/com/github/jk1/license/filter/LicenseBundleNormalizer.groovy#L179

**Comment by Poeschl** [comment]
Commit 97dba48 fixed it. I forgot to escape the `\`.
Also made some adjustments on the matchers and added PUBLIC DOMAIN.

**Comment by jk1** [comment]
Thanks for the contribution.
Please find it merged.

**Comment by guenhter** [comment]
@Poeschl Nice to have tests, isn't it :)

**Comment by Poeschl** [comment]
Totally with you. Way to less on way to many projects.

**Pull request merged**
